name: Code analysis

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest

    name: Running tests
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pytest pytest-cov pylint flake8
          python -m pip install -r requirements.txt

      - name: Test with PyTest
        run: pytest --cov=motionblindsble --cov-report term-missing

      - name: Generate PyTest coverage badge
        uses: tj-actions/coverage-badge-py@v2
        with:
          output: '.github/badges/coverage.svg'

      - name: Get last commit message
        id: last-commit
        run: |
          echo "message=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT
          echo "author=$(git log -1 --pretty=\"%an <%ae>\")" >> $GITHUB_OUTPUT

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: ${{ steps.last-commit.outputs.author }}
          commit_message: ${{ steps.last-commit.outputs.message }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true

      - name: Analyse the code with Pylint
        run: |
          pylint motionblindsble

      - name: Analyse the code with Flake8
        run: |
          flake8 motionblindsble --count --exit-zero --max-line-length=130 --statistics
