name: Release Python Package to PyPi

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  verify:
    name: Verify Python build
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pylint

  build:
    name: Build and publish to PyPi
    needs: verify
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build

    - name: Extract release version
      id: release_version
      run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

    - name: Update version in setup.py
      run: sed -i "s/{{VERSION_PLACEHOLDER}}/${{ steps.release_version.outputs.VERSION }}/g" setup.py

    - name: Build package
      run: python setup.py sdist

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}